"""
60-question compatibility quiz across 6 categories (10 questions each).
Answers are 1-5 scale. Categories:
  0  — Attachment Style
  1  — Communication
  2  — Values & Life Goals
  3  — Love Languages
  4  — Lifestyle
  5  — Conflict Resolution
"""

CATEGORIES = [
    "Attachment Style",
    "Communication",
    "Values & Life Goals",
    "Love Languages",
    "Lifestyle",
    "Conflict Resolution",
]

QUESTIONS = [
    # ── Attachment Style (0-9) ──────────────────────────────────────────────
    {"id": 0,  "category": 0, "text": "How comfortable are you with emotional vulnerability in a relationship?",
     "options": ["Very uncomfortable", "Somewhat uncomfortable", "Neutral", "Somewhat comfortable", "Very comfortable"]},
    {"id": 1,  "category": 0, "text": "When your partner is distant, how do you typically respond?",
     "options": ["Withdraw completely", "Feel anxious and pull back", "Give space and wait", "Gently check in", "Openly express my needs"]},
    {"id": 2,  "category": 0, "text": "How much personal space do you need in a relationship?",
     "options": ["Very little — I want constant togetherness", "Less than average", "A balanced mix", "More than average", "A lot — I value independence highly"]},
    {"id": 3,  "category": 0, "text": "How do you handle feelings of jealousy?",
     "options": ["I get very jealous and struggle to contain it", "I get jealous but keep it mostly internal", "I feel it mildly and process it", "I rarely feel jealous", "I almost never feel jealous"]},
    {"id": 4,  "category": 0, "text": "How quickly do you typically feel secure in a new relationship?",
     "options": ["I rarely feel fully secure", "It takes a very long time", "Several months", "A few weeks", "Fairly quickly once I trust someone"]},
    {"id": 5,  "category": 0, "text": "How do you feel about your partner having close friendships with exes?",
     "options": ["Very uncomfortable", "Somewhat uncomfortable", "Neutral with clear boundaries", "Fine with transparency", "Completely fine"]},
    {"id": 6,  "category": 0, "text": "How do you respond when a partner needs more reassurance than you expected?",
     "options": ["I find it draining and pull away", "I try but feel overwhelmed", "I adapt if communicated clearly", "I naturally offer reassurance", "I love being someone's safe space"]},
    {"id": 7,  "category": 0, "text": "How important is it that your partner is your primary emotional support?",
     "options": ["Not important — I rely on myself", "Slightly important", "Moderately important", "Very important", "Essential — they must be my main support"]},
    {"id": 8,  "category": 0, "text": "How do you feel about discussing your childhood wounds with a partner?",
     "options": ["I never would", "Very reluctantly", "Only after years of trust", "Once trust is established", "I believe deep sharing is essential"]},
    {"id": 9,  "category": 0, "text": "When you sense your partner pulling away, what is your instinct?",
     "options": ["Chase and pursue immediately", "Feel anxious but wait", "Give space and observe", "Trust the relationship and stay steady", "Completely give them space"]},

    # ── Communication (10-19) ────────────────────────────────────────────────
    {"id": 10, "category": 1, "text": "How do you prefer to resolve misunderstandings?",
     "options": ["Avoid until it passes", "Text or written message", "Give it a day then talk", "Talk it out immediately", "Schedule a dedicated conversation"]},
    {"id": 11, "category": 1, "text": "How often do you like to communicate with a partner throughout the day?",
     "options": ["A few times a week", "Once a day", "A few times a day", "Frequently throughout the day", "Constantly — I love staying connected"]},
    {"id": 12, "category": 1, "text": "How comfortable are you expressing your emotional needs directly?",
     "options": ["I rarely can", "I struggle but try", "Sometimes", "Usually yes", "Always — it feels natural"]},
    {"id": 13, "category": 1, "text": "How do you respond to criticism from a partner?",
     "options": ["I shut down", "I become defensive initially", "I take time to process then respond", "I try to hear it openly", "I welcome it as growth"]},
    {"id": 14, "category": 1, "text": "How important is having deep intellectual conversations with a partner?",
     "options": ["Not important", "Slightly important", "Moderately important", "Very important", "Essential to my connection"]},
    {"id": 15, "category": 1, "text": "How do you communicate when you are upset?",
     "options": ["I go silent", "I need a lot of alone time first", "I journal then share", "I share after a short cooldown", "I express it fairly directly"]},
    {"id": 16, "category": 1, "text": "How do you feel about your partner expressing hard truths?",
     "options": ["I prefer they soften everything", "I prefer gentle delivery", "Balance of honesty and sensitivity", "I appreciate directness", "I strongly value radical honesty"]},
    {"id": 17, "category": 1, "text": "How much do you value humor and lightness in daily relationship communication?",
     "options": ["Not important at all", "Slightly important", "Moderately important", "Very important", "Essential — laughter is core to us"]},
    {"id": 18, "category": 1, "text": "How do you handle it when a partner interrupts you during conversations?",
     "options": ["It deeply bothers me and I disengage", "I find it frustrating", "I note it and address it later", "I gently redirect", "It doesn't bother me much"]},
    {"id": 19, "category": 1, "text": "How important is it that your partner remembers the small details you share?",
     "options": ["Not important", "Slightly", "Moderately", "Very important", "It means everything to me"]},

    # ── Values & Life Goals (20-29) ──────────────────────────────────────────
    {"id": 20, "category": 2, "text": "How important are religious or spiritual beliefs in your life?",
     "options": ["Not at all important", "Slightly important", "Somewhat important", "Very important", "Central to my identity"]},
    {"id": 21, "category": 2, "text": "Do you want children in the future?",
     "options": ["Definitely not", "Probably not", "Open to it", "Probably yes", "Definitely yes"]},
    {"id": 22, "category": 2, "text": "How important is financial ambition to you?",
     "options": ["Not important — I value simplicity", "Slightly important", "Moderately important", "Very important", "Extremely — building wealth is a core goal"]},
    {"id": 23, "category": 2, "text": "How do you feel about traditional relationship roles?",
     "options": ["I strongly prefer non-traditional", "I lean non-traditional", "I like a mix", "I lean traditional", "I strongly prefer traditional"]},
    {"id": 24, "category": 2, "text": "How important is personal freedom and autonomy in your life?",
     "options": ["I prioritize partnership over independence", "Slightly important", "Balanced", "Very important", "Essential — independence is non-negotiable"]},
    {"id": 25, "category": 2, "text": "How important is community and social connection to you?",
     "options": ["Not important — I'm very introverted", "Slightly", "Moderate", "Very", "Essential — my community is central to my life"]},
    {"id": 26, "category": 2, "text": "How do you prioritize career vs relationship?",
     "options": ["Relationship always comes first", "Relationship usually first", "Equal balance", "Career usually first", "Career always comes first"]},
    {"id": 27, "category": 2, "text": "How do you view personal growth and self-development?",
     "options": ["Not a priority", "Occasionally pursue it", "I engage when inspired", "Active pursuit is important", "It is a core lifestyle commitment"]},
    {"id": 28, "category": 2, "text": "How do you feel about living in the same city your whole life vs relocating?",
     "options": ["Strong roots — I never want to relocate", "Prefer to stay", "Open to it under the right circumstances", "Likely to relocate", "I plan to relocate or travel extensively"]},
    {"id": 29, "category": 2, "text": "How important is it that your partner shares your core values?",
     "options": ["Not very — differences are fine", "Slightly important", "Somewhat important", "Very important", "Non-negotiable — we must be aligned"]},

    # ── Love Languages (30-39) ───────────────────────────────────────────────
    {"id": 30, "category": 3, "text": "How important is physical affection (hugs, touch, closeness) to you?",
     "options": ["Not important", "Slightly", "Moderately", "Very", "Essential daily"]},
    {"id": 31, "category": 3, "text": "How much do words of affirmation (compliments, verbal love) mean to you?",
     "options": ["Not important", "Nice but not needed", "Moderately important", "Very important", "I need it to feel loved"]},
    {"id": 32, "category": 3, "text": "How important is quality time (undivided attention) to feeling loved?",
     "options": ["Not important", "Slightly", "Moderately", "Very", "It is my primary love language"]},
    {"id": 33, "category": 3, "text": "How meaningful are acts of service (partner doing things for you) to you?",
     "options": ["Not meaningful", "Slightly", "Moderately", "Very meaningful", "It is how I feel most loved"]},
    {"id": 34, "category": 3, "text": "How important are thoughtful gifts as expressions of love?",
     "options": ["Not important at all", "Nice but optional", "Moderately", "Very important", "Essential to feeling valued"]},
    {"id": 35, "category": 3, "text": "How do you most naturally express love to a partner?",
     "options": ["Through physical closeness", "Through verbal expressions", "Through dedicated time", "Through helpful actions", "Through thoughtful gestures"]},
    {"id": 36, "category": 3, "text": "How do you feel when a partner surprises you with a small romantic gesture?",
     "options": ["Awkward or indifferent", "Mildly appreciative", "Happy but it's not important", "Genuinely moved", "It is deeply meaningful to me"]},
    {"id": 37, "category": 3, "text": "How important is it to have regular dedicated date nights?",
     "options": ["Not important", "Nice occasionally", "Monthly is enough", "Weekly ideally", "Essential to my connection"]},
    {"id": 38, "category": 3, "text": "How do you prefer your partner to show up when you're having a hard day?",
     "options": ["Give me space", "Send a kind text", "Be present and listen", "Help me solve the problem", "Hold me and comfort me physically"]},
    {"id": 39, "category": 3, "text": "How important is maintaining romantic energy long into a relationship?",
     "options": ["Not very — comfort matters more", "Slightly", "Moderately", "Very important", "Non-negotiable — romance must stay alive"]},

    # ── Lifestyle (40-49) ────────────────────────────────────────────────────
    {"id": 40, "category": 4, "text": "How would you describe your ideal living environment?",
     "options": ["Rural or very quiet", "Small town", "Suburbs", "Urban — city energy", "Major metropolitan city"]},
    {"id": 41, "category": 4, "text": "How active is your social life?",
     "options": ["Very private — rarely social", "Small gatherings occasionally", "Balanced mix", "Frequently social", "Very active — always socializing"]},
    {"id": 42, "category": 4, "text": "How important is fitness and physical health in your daily life?",
     "options": ["Not important", "Slightly", "Moderately — I stay reasonably active", "Very important", "Central — fitness is a lifestyle"]},
    {"id": 43, "category": 4, "text": "How do you feel about alcohol and social drinking?",
     "options": ["I don't drink and prefer a partner who doesn't", "I rarely drink", "Socially occasionally", "I enjoy it regularly", "It is an important part of my social life"]},
    {"id": 44, "category": 4, "text": "How important is travel to you?",
     "options": ["Not important", "Occasionally nice", "A few trips a year", "Frequent travel is important", "Travel is a core life priority"]},
    {"id": 45, "category": 4, "text": "How do you prefer to spend a typical weekend?",
     "options": ["Totally at home recharging", "Mostly home with one outing", "Mix of home and social activity", "Mostly out and active", "Always out exploring or socializing"]},
    {"id": 46, "category": 4, "text": "How important are shared hobbies with a partner?",
     "options": ["Not important — I prefer separate interests", "Slightly nice", "Good to have some overlap", "Very important", "We should share most interests"]},
    {"id": 47, "category": 4, "text": "How do you feel about pets?",
     "options": ["I dislike pets", "I'm neutral", "I like them but don't need them", "I love them and want them", "Pets are family — non-negotiable"]},
    {"id": 48, "category": 4, "text": "How important is financial compatibility (similar spending habits)?",
     "options": ["Not important", "Slightly", "Moderately", "Very important", "Essential — misalignment would end it"]},
    {"id": 49, "category": 4, "text": "How much time do you ideally spend together vs apart each week?",
     "options": ["Mostly apart — independence first", "More apart than together", "Roughly equal", "More together than apart", "As much time together as possible"]},

    # ── Conflict Resolution (50-59) ──────────────────────────────────────────
    {"id": 50, "category": 5, "text": "How do you typically handle the first sign of tension in a relationship?",
     "options": ["Avoid completely", "Minimize and move on", "Acknowledge and take space", "Address it calmly soon", "Address it immediately"]},
    {"id": 51, "category": 5, "text": "How long do you typically need after a fight before reconnecting?",
     "options": ["Days or more", "At least a day", "Several hours", "An hour or two", "I want to resolve it right away"]},
    {"id": 52, "category": 5, "text": "How do you respond when you feel unheard in an argument?",
     "options": ["I completely shut down", "I get louder or more intense", "I ask to pause and revisit", "I restate my perspective calmly", "I try to understand their view first"]},
    {"id": 53, "category": 5, "text": "How comfortable are you apologizing first?",
     "options": ["Very uncomfortable — I wait for them", "I struggle but can", "It depends on who was wrong", "I'm fairly comfortable", "I apologize readily if I was wrong"]},
    {"id": 54, "category": 5, "text": "How do you feel about professional couples therapy or counseling?",
     "options": ["Against it entirely", "Would only consider it in crisis", "Open to it if needed", "Would actively consider it proactively", "I believe all couples should do it"]},
    {"id": 55, "category": 5, "text": "How do you handle ongoing unresolved issues in a relationship?",
     "options": ["Ignore them hoping they pass", "Bring them up occasionally", "Revisit when calm", "Consistently work through them", "Systematically address them proactively"]},
    {"id": 56, "category": 5, "text": "How do you feel when your partner raises a recurring complaint?",
     "options": ["Defensive and resentful", "Defensive but I try to listen", "I acknowledge but struggle", "I receive it and reflect", "I appreciate the honesty and engage"]},
    {"id": 57, "category": 5, "text": "How much do past relationship patterns affect your current reactions?",
     "options": ["A lot — I carry significant wounds", "Quite a bit", "Somewhat", "A little", "Very little — I've done the work"]},
    {"id": 58, "category": 5, "text": "How do you feel about using humor to diffuse tension?",
     "options": ["Inappropriate — it minimizes the issue", "I'm cautious about it", "Context dependent", "I appreciate it if timed well", "I love it — lightness heals us"]},
    {"id": 59, "category": 5, "text": "How important is full resolution before moving on after conflict?",
     "options": ["I can move on without full resolution", "I prefer resolution but can adapt", "It depends on the issue", "Resolution is very important", "We must fully resolve before moving on"]},
]
